import type { DragonType } from "../../types/dragon";

export const DRAGON_ITEMS: DragonType[] = [
    {
        id: "dragon:lumie",
        name: "Lumie",
        description: "A gentle light dragon who's always by your side. Your first companion and loyal friend.",
        price: undefined, 
        rarity: "legendary",
        canFly: true,
        facesLeft: true,
        baseGenerationRate: 5,
        imagePath: "/images/dragons/lumie/Lumie_transparent.png",
    },
    {
        id: "dragon:fire",
        name: "Flame",
        description: "A fierce fire dragon with burning passion. Leaves trails of embers wherever it flies.",
        price: 2000,
        rarity: "common",
        canFly: true,
        facesLeft: true,
        baseGenerationRate: 1,
        imagePath: "/images/dragons/fire.png",
    },
    {
        id: "dragon:water",
        name: "Water",
        description: "A calm water dragon that flows like a river. Brings tranquility and steady growth.",
        price: 2500,
        rarity: "common",
        canFly: false,
        facesLeft: false,
        baseGenerationRate: 1,
        imagePath: "/images/dragons/water.png",
    },
    {
        id: "dragon:wind",
        name: "Wind",
        description: "A swift wind dragon that dances through the air. Free-spirited and graceful.",
        price: 3500,
        rarity: "common",
        canFly: true,
        facesLeft: true,
        baseGenerationRate: 1,
        imagePath: "/images/dragons/wind.png",
    },
    {
        id: "dragon:flora",
        name: "Leaf",
        description: "A nature dragon adorned with flowers and vines. Nurtures growth wherever it roams.",
        price: 4500,
        rarity: "rare",
        canFly: true,
        facesLeft: true,
        baseGenerationRate: 2,
        imagePath: "/images/dragons/flora.png",
    },
    {
        id: "dragon:stone",
        name: "Stone",
        description: "A sturdy stone dragon with unbreakable resolve. Solid as a rock and twice as dependable.",
        price: 5500,
        rarity: "rare",
        canFly: false,
        facesLeft: true,
        baseGenerationRate: 2,
        imagePath: "/images/dragons/stone.png",
    },
    {
        id: "dragon:power",
        name: "Lightning",
        description: "A power dragon radiating raw energy. Commands respect from all who see it.",
        price: 6500,
        rarity: "rare",
        canFly: false,
        facesLeft: false,
        baseGenerationRate: 2,
        imagePath: "/images/dragons/power.png",
    },
    {
        id: "dragon:ice",
        name: "Snow",
        description: "A crystalline ice dragon that glitters in the light. Cool and collected, yet powerful.",
        price: 7500,
        rarity: "epic",
        canFly: true,
        facesLeft: true,
        baseGenerationRate: 3,
        imagePath: "/images/dragons/ice.png",
    },
    {
        id: "dragon:steel",
        name: "Steel",
        description: "A metallic steel dragon with armor-like scales. Unyielding strength and determination.",
        price: 9500,
        rarity: "epic",
        canFly: true,
        facesLeft: true,
        baseGenerationRate: 3,
        imagePath: "/images/dragons/steel.png",
    },
    {
        id: "dragon:lucky",
        name: "Fortune",
        description: "A mystical lucky dragon blessed by fate. Brings prosperity and good fortune.",
        price: 11500,
        rarity: "legendary",
        canFly: true,
        facesLeft: false,
        baseGenerationRate: 5,
        imagePath: "/images/dragons/lucky.png",
    },
    {
        id: "dragon:dawn",
        name: "Dawn",
        description: "A radiant dawn dragon that heralds new beginnings. Shines with the light of a new day.",
        price: 13500,
        rarity: "legendary",
        canFly: true,
        facesLeft: false,
        baseGenerationRate: 5,
        imagePath: "/images/dragons/dawn.png",
    },
    {
        id: "dragon:dusk",
        name: "Dusk",
        description: "A mysterious dusk dragon cloaked in evening shadows. Bridges day and night with elegance.",
        price: 15500,
        rarity: "legendary",
        canFly: true,
        facesLeft: true,
        baseGenerationRate: 5,
        imagePath: "/images/dragons/dusk.png",
    },
    {
        id: "dragon:shad",
        name: "Thunder",
        description: "A powerful thunder dragon that commands the skies with its mighty roar. Leaves trails of lightning wherever it flies.",
        price: 20000,
        rarity: "legendary",
        canFly: true,
        facesLeft: false,
        baseGenerationRate: 5,
        imagePath: "/images/dragons/shad.png",
    },
];

// Helper function to get dragon by ID
export function getDragonById(id: string): DragonType | undefined {
    return DRAGON_ITEMS.find(dragon => dragon.id === id);
}

// Helper to get rarity color
export function getRarityColor(rarity: DragonType["rarity"]): string {
    const colors = {
        common: "#9CA3AF",
        rare: "#3B82F6",
        epic: "#A855F7",
        legendary: "#F59E0B",
    };
    return colors[rarity];
}
